name: 'AWS Lambda Terraform GitHub Actions'
on: 
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      run: terraform validate -no-color
      env:
        TF_VAR_mqtt_username: ${{ secrets.TF_VAR_mqtt_username }}
        TF_VAR_mqtt_password: ${{ secrets.TF_VAR_mqtt_password }}
        TF_VAR_mqtt_broker: ${{ secrets.TF_VAR_mqtt_broker }}

    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve
      env:
        TF_VAR_mqtt_username: ${{ secrets.TF_VAR_mqtt_username }}
        TF_VAR_mqtt_password: ${{ secrets.TF_VAR_mqtt_password }}
        TF_VAR_mqtt_broker: ${{ secrets.TF_VAR_mqtt_broker }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}